### ISSUE TITLE
reviews du tuto-github

### ISSUE THREAD

**Issue by Madame-K** [chemins-de-la-transition/tuto-github#11]
Pouvez me faire des retours sur [ce tuto](https://github.com/chemins-de-la-transition/tuto-github/blob/master/README.md) ? Est il clair ? Vous est il utile ? Avez vous envie de savoir d'autres choses ? Lâchez vous...

**Comment by GuillaumeAV** [comment]
Il est trop bien ton tuto @Madame-K !!

**Comment by ircocomat** [comment]
Super , clair, peut être Revoir la mis en page si on peut mais c'est assez complet ! 
Merci !

**Comment by Mathieu-CdlT** [comment]
Haha, bon moi j'ai quelques commentaires.... 

1. C'est trop bien que tu aies fait ça :) :) :) !!!

2. Je traduirais les termes en Anglais, au moins une fois, genre "issue", même si tu le fais ds le texte et sur ta carte heuristique, ca vaudrait le coup que ds le tuto ne subsistent pas des interrogations. 

2. Après le point 2, je mettrais un point tuto sur "Projets et kanban", sur l'intégration des issues ds le pgme de travail. Les issues juste pour les issues sinon, c'est ingérable, on a un besoin de tri et d'organisation des issues en gestion de projet - et c'est l'intéret de github si j'ai bien compris. + fonction add cards. 

3. Point #4 : ca me perturbe, voire me perd. "comment faire les dépots a distance". En fait je comprends pas et n'ai pas les infos qui renvoient vers plus de précisions sur CodiMD.... Je suggérerais de faire un tuto simple de bout en bout, pour une prise en main, sans complications ; que les fonctionnalités basiques qu'on utilise de Github puissent être utilisables par tout nouvel arrivant, et puis peut être plus bas une rubrique "pour aller plus loin" avec des infos plus touchy pour celleux qui s'en sentent... (dont le point #4). 

Voilà pour mes apports en première lecture rapide. 
Merci en tout cas pour ce travail :) !
